name: 'AgentWatch'
description: 'File-targeted agent monitoring system with pattern matching'
author: 'whichguy'
branding:
  icon: 'eye'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  pattern:
    description: 'File pattern to watch (e.g., *.js, src/**/*.ts)'
    required: false
  agent:
    description: 'Agent to run'
    required: false
  agent-args:
    description: 'Arguments to pass to the agent'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout AgentWatch
      uses: actions/checkout@v4
      with:
        repository: whichguy/agentwatch
        path: .agentwatch
        
    - name: Run AgentWatch
      shell: bash
      run: |
        # Run the actual agentwatch logic
        .agentwatch/.github/scripts/agentwatch.sh "${{ inputs.pattern }}" "${{ inputs.agent }}" "${{ inputs.agent-args }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}